### ISSUE TITLE
1.21 Applied Flux - output limit on induction card

### ISSUE THREAD

**Issue by jinkhya** [GlodBlock/ExtendedAE#277]
Hello,
I couldn't find the info anywhere so here I am :) I'm trying to use the induction card into a pattern provider which would power my Mekanism ultimate machine. If I put maximum energy upgrades on the mek machine it's fine, but otherwise the power isn't keeping up. Am I missing something or there's a threshold on those cards ? I thought maybe if I were using a higher tier of FE storage cells it'd push more power but that doesn't seem to affect it either.
Thanks in advance,
Jin

**Comment by gitBurmecia** [comment]
Also noticing this on all my MI machines, they completely lost efficiency because the induction cards aren't pushing enough power. Appliedflux completely turns off when it senses the machine's power buffer is full, and doesn't turn back on again until a few ticks later, this causes it to be effectively useless for a majority of applications.

**Comment by GlodBlock** [comment]
it should be fixed in the latest appflux
